on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - name: npm install
#        uses: actions/npm@master
#        with:
#          args: install
#      - name: npm test
#        uses: actions/npm@master
#        with:
#          args: run test
#      - name: npm lint
#        uses: actions/npm@master
#        with:
#          args: run lint
#      - name: docker build
#        uses: actions/docker/cli@master
#        with:
#          args: build -t abhinavdhasmana/github-action-example-node .
          
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
    # Server address of Docker registry. If not set then will default to Docker Hub
          registry: guidedadder.azurecr.io
    # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_PASSWORD }}
    # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_USERNAME }}
#      - name: docker push
#        uses: actions/docker/cli@master
#        with:
#          args: push abhinavdhasmana/github-action-example-node
